spring:
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    baseline-on-migrate: true
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
security:
  jwt:
    secret: 61388b4a-c27a-331e-b301-150c0701cee4
    expiration: 900

client:
  url: https://run.mocky.io/v3/4abec2b1-4f6d-4c08-b3cd-eda87bed56e5