CREATE TABLE TB_USERS (
    ID UUID NOT NULL PRIMARY KEY,
    EMAIL VARCHAR(70) NOT NULL UNIQUE,
    PASSWORD VARCHAR(50) NOT NULL,
    TAX_NUMBER VARCHAR(15) NOT NULL UNIQUE,
    FULL_NAME VARCHAR(70) NOT NULL,
    TYPE VARCHAR(30) NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME
);