CREATE TABLE TB_TRANSACTION_PIN (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PIN VARCHAR(50) NOT NULL,
    ATTEMPT INT NOT NULL,
    BLOCKED Bool NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME
);