CREATE TABLE TB_WALLETS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    BALANCE DECIMAL(10, 2) NOT NULL,
    ID_USER UUID NOT NULL UNIQUE,
    ID_TRANSACTION_PIN BIGINT NOT NULL UNIQUE,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME,

    FOREIGN KEY (ID_USER) REFERENCES TB_USERS(ID),
    FOREIGN KEY (ID_TRANSACTION_PIN) REFERENCES TB_TRANSACTION_PIN(ID)
);