CREATE TABLE TB_TRANSACTIONS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FROM_WALLET BIGINT NOT NULL,
    TO_WALLET BIGINT NOT NULL,
    TRANSACTION_VALUE DECIMAL(10, 2) NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME,

    CONSTRAINTS FOREIGN KEY (FROM_WALLET) REFERENCES TB_TRANSACTIONS(FROM_WALLET)
    CONSTRAINTS FOREIGN KEY (TO_WALLET) REFERENCES TB_TRANSACTIONS(TO_WALLET)
);